receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins: ["http://*", "https://*"]
# Processors
processors:
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
  batch:
    timeout: 10s
    send_batch_size: 1024
  resourcedetection:
    detectors: [env, system]
  transform:
    error_mode: ignore
    trace_statements:
      - context: span
        statements:
          - replace_pattern(attributes["url.path"], "\\?.*", "")
          - replace_pattern(name, "\\?.*", "")
          - replace_pattern(name, "GET /api/products/[^/]+", "GET /api/products/{productId}")
          - set(attributes["db_system_name"], attributes["db.system.name"]) where attributes["db.system.name"] != nil
          - set(attributes["code_function_name"], attributes["code.function.name"]) where attributes["code.function.name"] != nil
          - set(attributes["user_agent_original"], attributes["user_agent.original"]) where attributes["user_agent.original"] != nil
          - set(attributes["upstream_cluster_name"], attributes["upstream_cluster.name"]) where attributes["upstream_cluster.name"] != nil
          - set(attributes["error_type"], attributes["error.type"]) where attributes["error.type"] != nil
          - set(attributes["app_ads_contextKeys"], attributes["app.ads.contextKeys"]) where attributes["app.ads.contextKeys"] != nil
          - set(attributes["rpc_system"], attributes["rpc.system"]) where attributes["rpc.system"] != nil
    log_statements:
      - context: log
        statements:
          - flatten(body, "")
          - merge_maps(body, body[""], "upsert")
          - delete_key(body, "")
          - set(body, Concat([body], ", ")) where IsMap(body)

# Exporters
exporters:
  debug:
    verbosity: detailed
  otlp/opensearch:
    endpoint: data-prepper:21890
    tls:
      insecure: true

# Service pipelines
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resourcedetection, memory_limiter, transform, batch]
      exporters: [otlp/opensearch, debug]
    logs:
      receivers: [otlp]
      processors: [resourcedetection, memory_limiter, transform, batch]
      exporters: [otlp/opensearch, debug]
  