# Stock Service
spring:
  application:
    name: xiaozhou-stock
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
  datasource:
    url: jdbc:mysql:///mytestshop?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2b8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: stock-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

# Server
server:
  port: 8091

# Management
management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
