# Data Prepper Pipeline Configuration
# OTLP Traces + Metrics to OpenSearch

# ============== Metrics Pipeline (from OTel Collector) ==============
otel-metrics-pipeline:
  source:
    otel_metrics_source:
      port: 21891
      ssl: false
  buffer:
    bounded_blocking:
      buffer_size: 5120
      batch_size: 512
  processor:
    - otel_metrics_raw_processor:
  sink:
    - opensearch:
        hosts:
          - "http://opensearch:9200"
        index_type: custom
        index: "metrics-otel-%{yyyy.MM.dd}"
        bulk_size: 20
        flush_timeout: 30

# ============== OTel Trace Pipeline ==============
# Entry pipeline: receive OTLP traces
entry-pipeline:
  source:
    otel_trace_source:
      port: 21890
      ssl: false
  buffer:
    bounded_blocking:
      buffer_size: 51200
      batch_size: 800
  sink:
    - pipeline:
        name: "raw-trace-pipeline"
    - pipeline:
        name: "service-map-pipeline"

# Raw trace processing pipeline
raw-trace-pipeline:
  source:
    pipeline:
      name: "entry-pipeline"
  buffer:
    bounded_blocking:
      buffer_size: 51200
      batch_size: 800
  processor:
    - otel_trace_raw:
  sink:
    - opensearch:
        hosts:
          - "http://opensearch:9200"
        index_type: trace-analytics-raw
        bulk_size: 20
        flush_timeout: 30

# Service map pipeline
service-map-pipeline:
  source:
    pipeline:
      name: "entry-pipeline"
  buffer:
    bounded_blocking:
      buffer_size: 51200
      batch_size: 800
  processor:
    - service_map_stateful:
        window_duration: 180
  sink:
    - opensearch:
        hosts:
          - "http://opensearch:9200"
        index_type: trace-analytics-service-map
        bulk_size: 20
        flush_timeout: 30
